[[section-building-block-view]]


== Building Block View
This section will show the static decomposition of the system into building blocks as well as their dependencies. We will zoom into black boxes of the different levels to show their components. 

For reference, we are going to use the scope and context diagram that has been described in the third section of the documentation.

Motivation::
The motivation of this diagram is to have a general vision of all different modules of the application.

=== Level 1

==== White Box Viade

At a first glance, we can identify the main modules that make up the application. We have the Viade Client modules developed in this project and SolidServer with whom it interacts.

image::Diagrams-5.2.1.svg[Viade First Level]

Contained Building Blocks::
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Viade Client | It allows users to share routes and multimedia.
| Solid Server | It provides the PODs which store the information. 
|===

Important Interfaces::
Client-Server high level communication (HTTP).

=== Level 2

==== White Box Viade Client

If we break down ViadeClient, we get three modules.They make use of an n-layer based architecture, namely three.

image::Diagrams-5.3.1.svg[Viade Client: Second Level]
Contained Building Blocks::

[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Route Module | It manages the routes and multimedia that users can share.
| Data Service Module | It links Front-End layer with SolidAdapter. Includes business logic and data models.
| Solid Adapter Module | Link between Viade and Solid Server.
|===

==== White Box Solid Server

External module to the project. For more indepth information relative to this blocks, click link:https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-2-0.pdf[here].

image::Diagrams-5.3.2.svg[Solid Server: Second Level]

Contained Building Blocks::
 * Authentication
 * Authorization
 * HTTP
 * LDP
 * Storage

=== Level 3
==== White Box Route Module

In this module you will find all the components that are related to the UI layer.

image::Diagrams-5.4.1.svg[Route Module: Third Level]

Contained Building Blocks::
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Login | It allows to log in to a Solid Server provider.
| Add route | Create new routes.
| My Routes | List routes were created by logged user.
| List friends | List your friends
| Register | It allows to sign up to a Solid Server provider.
| Add Milestone | Create a new point.
| Shared Routes | Share created route.
| Inboxes | Inbox with received notifications.
|===

==== White Box Data Service Module

The decomposition of DataService is complex. On the one hand, we have the services in relation to Solid User, Friend Service and NotificationService. On the other hand, we have the services for route management.

image::Diagrams-5.4.2.svg[Data Service Module: Third Level]

Contained Building Blocks::
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Friend Service | User friends are managed.
| Route Service | It manages all actions relative to routes.
| Milestone Service | It manages all actions relative to milestones.
| Notification Service | When a user shares a route, it allows to publish and suscribe a notification.
| Comment Service | Allows publish and get messages.
| Media Service | It manages the processing of media.
|===

==== White Box Solid Adapter Module

Finally, the lowest level module is SolidAdapter. It provides us with the logic for the necessary interaction with RDF. It looks similar to an ORM (Object Relational Object). 

image::Diagrams-5.4.3.svg[Solid Adapter Module: Third Level]

Contained Building Blocks::
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Solid Adapter | Link between DataModel and Solid Helper. First layer with fundamental functions.
| Solid Helper | It distributes work among low-level modules.
| LdFlex | Low-level functions that manage SPARQL query and create Turtle files.
| Notification | Low-level functions that create and receive notifications.
| Storage | Low-level  functions that allow to manage Solid's POD.
| Permission | Low-level functions which allows to control the ACL.
|===
